[local]
localhost

[mongodb]
localhost

[catalogue]
localhost

[cart]
localhost

[user]
localhost

[redis]
localhost

[mysql]
localhost

[rabbitmq]
localhost


[shipping]
localhost

[payment]
localhost

[frontend]
localhost
